name = "shop-demo-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "shop-demo-db"
database_id = "da700c96-7bdc-44f9-9bf2-75131581fd78"
